import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import Card, { CardHeader, CardBody } from '../components/ui/Card';
import Badge from '../components/ui/Badge';
import Button from '../components/ui/Button';
import { Download, FileText, ShieldAlert, GitBranch, Lightbulb, Map, FileSignature, Radar, CheckCircle } from 'lucide-react';
import { getAllAnalyses } from '../utils/analysisStore';
import '../components/dashboard/Dashboard.css';

const getRiskColor = (level) => {
  if (level === 'High') return 'var(--danger)';
  if (level === 'Medium') return 'var(--warning)';
  if (level === 'Low') return 'var(--success)';
  return 'var(--text-secondary)';
};

const Reports = () => {
  const location = useLocation();
  const [analyses, setAnalyses] = useState([]);
  const [selectedAnalysisId, setSelectedAnalysisId] = useState('');
  const [monitors, setMonitors] = useState([]);
  const [activeMonitor, setActiveMonitor] = useState(null);

  useEffect(() => {
    const loaded = getAllAnalyses();
    setAnalyses(loaded);
    if (loaded.length > 0) {
      if (location.state?.selectedAnalysisId) {
        setSelectedAnalysisId(location.state.selectedAnalysisId);
      } else {
        setSelectedAnalysisId(loaded[0].id);
      }
    }
    
    // Fetch monitors to link monitoring data
    fetch('http://localhost:8000/monitors')
      .then(res => res.json())
      .then(data => setMonitors(data))
      .catch(console.error);
  }, []);

  const selectedAnalysis = analyses.find(a => a.id === selectedAnalysisId);

  useEffect(() => {
    if (selectedAnalysis && monitors.length > 0) {
      const match = monitors.find(m => m.summary === selectedAnalysis.summary);
      setActiveMonitor(match || null);
    } else {
      setActiveMonitor(null);
    }
  }, [selectedAnalysis, monitors]);

  const handlePrintPDF = () => {
    window.print();
  };

  const handleExportDOCX = () => {
    if (!selectedAnalysis) return;
    
    // Create a very basic HTML structure for DOCX blob
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>IP Intelligence Report</title></head>
      <body style="font-family: Arial, sans-serif;">
        <h1 style="text-align:center;">IP Intelligence Report</h1>
        <h2 style="text-align:center;">${selectedAnalysis.title}</h2>
        <p style="text-align:center;">Generated by IPSentinel AI</p>
        
        <h3>1. Executive Summary</h3>
        <p>${selectedAnalysis.summary}</p>
        
        <h3>2. Risk Analysis</h3>
        ${selectedAnalysis.riskData ? `
          <p>Overall Score: ${selectedAnalysis.riskData.overall_score}</p>
          <p>Overall Risk: ${selectedAnalysis.riskData.overall_risk}</p>
        ` : '<p>Not available</p>'}
        
        <h3>3. Mitigations</h3>
        ${selectedAnalysis.mitigationData ? `
          <ul>
            ${selectedAnalysis.mitigationData.map(m => `<li>${m.suggested_design_around}</li>`).join('')}
          </ul>
        ` : '<p>Not available</p>'}
        
        <h3>4. What-If Simulation</h3>
        ${selectedAnalysis.whatIfData ? `
          <p>Original Score: ${selectedAnalysis.whatIfData.original_score} -> Modified Score: ${selectedAnalysis.whatIfData.modified_score}</p>
          <p>Original Risk: ${selectedAnalysis.whatIfData.original_risk} -> Modified Risk: ${selectedAnalysis.whatIfData.modified_risk}</p>
        ` : '<p>Not available</p>'}
        
        <h3>5. Draft Assistant</h3>
        ${selectedAnalysis.draftData ? `
          <p><strong>Title:</strong> ${selectedAnalysis.draftData.title}</p>
          <p><strong>Abstract:</strong> ${selectedAnalysis.draftData.abstract}</p>
        ` : '<p>Not available</p>'}
      </body>
      </html>
    `;
    
    const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `IP_Report_${selectedAnalysis.id}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (analyses.length === 0) {
    return (
      <div className="page-container">
        <div className="dashboard-header">
          <div className="dashboard-title-area">
            <h1 className="dashboard-title">Reports</h1>
            <p className="dashboard-subtitle">Export and share comprehensive IP intelligence reports.</p>
          </div>
        </div>
        <Card>
          <CardBody style={{ textAlign: 'center', padding: '64px' }}>
            <FileText size={48} style={{ color: 'var(--text-tertiary)', margin: '0 auto 24px' }} />
            <h3 style={{ color: 'var(--text-primary)', marginBottom: '8px' }}>No Analysis Available</h3>
            <p style={{ color: 'var(--text-secondary)' }}>Start a new analysis to generate an intelligence report.</p>
          </CardBody>
        </Card>
      </div>
    );
  }

  const { analysisData, searchData, riskData, mitigationData, whatIfData, mentorData, landscapeData, draftData } = selectedAnalysis;

  return (
    <div className="page-container">
      <div className="dashboard-header no-print">
        <div className="dashboard-title-area">
          <span className="dashboard-label">System</span>
          <h1 className="dashboard-title">Reports</h1>
          <p className="dashboard-subtitle">Export and share comprehensive IP intelligence reports.</p>
        </div>
      </div>

      <div className="reports-layout" style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }}>
        <div className="no-print" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <Card>
            <CardHeader title="Generate Custom Report" />
            <CardBody>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                  <label style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Select Analysis</label>
                  <select 
                    value={selectedAnalysisId} 
                    onChange={e => setSelectedAnalysisId(e.target.value)}
                    style={{ padding: '12px', background: 'var(--bg-app)', border: '1px solid var(--border-color)', borderRadius: '8px', color: 'var(--text-primary)', outline: 'none' }}
                  >
                    {analyses.map(a => (
                      <option key={a.id} value={a.id}>{a.title} ({new Date(a.createdAt).toLocaleDateString()})</option>
                    ))}
                  </select>
                </div>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '16px' }}>
                  <label style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Format</label>
                  <div style={{ display: 'flex', gap: '12px' }}>
                    <Button variant="primary" onClick={handlePrintPDF} style={{ flex: 1, display: 'flex', justifyContent: 'center', gap: '8px' }}><Download size={16} /> PDF</Button>
                    <Button variant="outline" onClick={handleExportDOCX} style={{ flex: 1, display: 'flex', justifyContent: 'center', gap: '8px' }}><FileText size={16} /> DOCX</Button>
                  </div>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>

        <div className="print-area" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <Card>
            <CardBody style={{ background: 'var(--bg-app)' }}>
              <div style={{ padding: '24px', background: 'var(--bg-surface)', border: '1px solid var(--border-color)', borderRadius: '8px' }}>
                <div style={{ textAlign: 'center', marginBottom: '32px' }}>
                  <h2 style={{ margin: '0 0 8px 0', color: 'var(--text-primary)' }}>IP INTELLIGENCE REPORT</h2>
                  <h3 style={{ margin: '0 0 16px 0', color: 'var(--accent-cyan)' }}>{selectedAnalysis.title}</h3>
                  <p style={{ margin: 0, color: 'var(--text-secondary)' }}>Generated by IPSentinel AI</p>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px', marginBottom: '32px' }}>
                  <div style={{ padding: '16px', border: '1px solid var(--border-color)', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ color: 'var(--success)', fontSize: '1.5rem', fontWeight: 700, marginBottom: '4px' }}>
                      {riskData ? (100 - riskData.overall_score) + '%' : 'N/A'}
                    </div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Novelty Score</div>
                  </div>
                  <div style={{ padding: '16px', border: '1px solid var(--border-color)', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ color: riskData ? getRiskColor(riskData.overall_risk) : 'var(--text-secondary)', fontSize: '1.5rem', fontWeight: 700, marginBottom: '4px' }}>
                      {riskData ? riskData.overall_risk : 'N/A'}
                    </div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Overall Risk</div>
                  </div>
                  <div style={{ padding: '16px', border: '1px solid var(--border-color)', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ color: 'var(--text-primary)', fontSize: '1.5rem', fontWeight: 700, marginBottom: '4px' }}>
                      {searchData ? searchData.length : 'N/A'}
                    </div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Relevant Patents</div>
                  </div>
                  <div style={{ padding: '16px', border: '1px solid var(--border-color)', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ color: 'var(--accent-cyan)', fontSize: '1.5rem', fontWeight: 700, marginBottom: '4px' }}>
                      {landscapeData ? landscapeData.opportunities?.length || 0 : 'N/A'}
                    </div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Opportunity Zones</div>
                  </div>
                </div>

                {/* 1. Invention Overview */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <FileText size={16} /> 1. Invention Overview
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    <p><strong>Summary:</strong> {selectedAnalysis.summary}</p>
                    {analysisData?.technical_features && (
                      <div style={{ marginTop: '12px' }}>
                        <strong>Technical Features:</strong>
                        <ul style={{ paddingLeft: '24px', marginTop: '8px' }}>
                          {analysisData.technical_features.map((f, i) => <li key={i}>{f}</li>)}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>

                {/* 2. Risk Analysis */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <ShieldAlert size={16} /> 2. Risk Analysis
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {riskData ? (
                      <ul style={{ paddingLeft: '24px' }}>
                        {riskData.heatmap_data?.map((item, i) => (
                          <li key={i} style={{ marginBottom: '8px' }}>
                            <strong style={{ color: getRiskColor(item.risk) }}>{item.risk} Risk:</strong> {item.explanation} (Matched Patent: {item.matched_patent_id})
                          </li>
                        ))}
                      </ul>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 3. Mitigation */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <Lightbulb size={16} /> 3. Mitigation & Design-Arounds
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {mitigationData ? (
                      <ul style={{ paddingLeft: '24px' }}>
                        {mitigationData.map((item, i) => (
                          <li key={i} style={{ marginBottom: '8px' }}>
                            <strong>Design Around:</strong> {item.suggested_design_around} <br/>
                            <em>Rationale: {item.why_it_is_risky}</em>
                          </li>
                        ))}
                      </ul>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 4. What-If Simulator */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <GitBranch size={16} /> 4. What-If Simulator Impact
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {whatIfData ? (
                      <div>
                        <p><strong>Risk Score:</strong> {whatIfData.original_score}/100 &rarr; {whatIfData.modified_score}/100</p>
                        <p><strong>Risk Level:</strong> {whatIfData.original_risk} &rarr; {whatIfData.modified_risk}</p>
                        <p><strong>Net Change:</strong> {whatIfData.modified_score - whatIfData.original_score} points</p>
                        <p style={{ marginTop: '12px' }}><strong>Modified Features:</strong></p>
                        <ul style={{ paddingLeft: '24px' }}>
                          {whatIfData.modified_features.map((f, i) => <li key={i}>{f}</li>)}
                        </ul>
                      </div>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 5. Innovation Mentor */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <CheckCircle size={16} /> 5. Innovation Mentor Insights
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {mentorData ? (
                      <div>
                        <p><strong>Latest Insight:</strong> {mentorData.answer}</p>
                        {mentorData.improvements?.length > 0 && (
                          <div style={{ marginTop: '12px' }}>
                            <strong>Suggested Improvements:</strong>
                            <ul style={{ paddingLeft: '24px' }}>
                              {mentorData.improvements.map((imp, i) => <li key={i}>{imp}</li>)}
                            </ul>
                          </div>
                        )}
                      </div>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 6. Patent Landscape */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <Map size={16} /> 6. Patent Landscape
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {landscapeData ? (
                      <div>
                        <p>Analyzed {landscapeData.total} patents to construct the landscape.</p>
                        {landscapeData.opportunities?.length > 0 && (
                          <div style={{ marginTop: '12px' }}>
                            <strong>Opportunity Zones (Low Density Clusters):</strong>
                            <ul style={{ paddingLeft: '24px' }}>
                              {landscapeData.opportunities.map((opp, i) => <li key={i}>{opp.description} (Risk: {opp.avgRisk})</li>)}
                            </ul>
                          </div>
                        )}
                      </div>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 7. Draft Assistant */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <FileSignature size={16} /> 7. Draft Assistant Highlights
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {draftData ? (
                      <div>
                        <p><strong>Title:</strong> {draftData.title}</p>
                        <p style={{ marginTop: '8px' }}><strong>Abstract:</strong> {draftData.abstract}</p>
                        {draftData.novelty_points?.length > 0 && (
                          <div style={{ marginTop: '12px' }}>
                            <strong>Novelty Points:</strong>
                            <ul style={{ paddingLeft: '24px' }}>
                              {draftData.novelty_points.map((p, i) => <li key={i}>{p}</li>)}
                            </ul>
                          </div>
                        )}
                      </div>
                    ) : <p>Not available — run this analysis to include it in the report.</p>}
                  </div>
                </div>

                {/* 8. IP Monitoring */}
                <div style={{ marginBottom: '32px' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', color: 'var(--text-primary)' }}>
                    <Radar size={16} /> 8. IP Monitoring Status
                  </h4>
                  <div style={{ padding: '16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    {activeMonitor ? (
                      <div>
                        <p><strong>Monitoring Status:</strong> Active</p>
                        <p><strong>Last Checked:</strong> {new Date(activeMonitor.last_checked).toLocaleString()}</p>
                        <p><strong>Total Matches:</strong> {activeMonitor.matches?.length || 0}</p>
                      </div>
                    ) : <p>Not available — this invention is not currently being monitored.</p>}
                  </div>
                </div>

                {/* Final Conclusion */}
                <div style={{ marginBottom: '32px', background: 'rgba(34, 211, 238, 0.05)', padding: '16px', borderRadius: '8px', border: '1px solid var(--accent-cyan)' }}>
                  <h4 style={{ color: 'var(--accent-cyan)', marginBottom: '8px' }}>Final IP Assessment</h4>
                  <p style={{ color: 'var(--text-primary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                    This consolidated report reflects the analysis journey of "{selectedAnalysis.title}". 
                    The overall risk profile is currently assessed as <strong>{riskData ? riskData.overall_risk : 'Unknown'}</strong>. 
                    Recommended next steps include addressing identified high-risk overlaps and continuously monitoring the landscape.
                  </p>
                </div>

                {/* Disclaimer */}
                <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '16px', textAlign: 'center' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)', lineHeight: 1.5 }}>
                    <strong>Legal Disclaimer:</strong> AI-generated insights are informational only and do not constitute legal advice, a patentability opinion, or an infringement opinion. Consult a qualified patent professional before filing or making legal decisions.
                  </p>
                </div>

              </div>
            </CardBody>
          </Card>
        </div>
      </div>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          .reports-layout { grid-template-columns: 1fr !important; display: block !important; }
          .page-container { padding: 0 !important; }
          .print-area { width: 100% !important; margin: 0 !important; }
          body { background: #fff; color: #000; }
          * { text-shadow: none !important; box-shadow: none !important; border-color: #ddd !important; }
          h2, h3, h4, p, li, strong, span, div { color: #000 !important; }
          CardBody { padding: 0 !important; }
        }
      `}</style>
    </div>
  );
};

export default Reports;
